export const CAMBIAR_DIFICULTAD = "CAMBIAR_DIFICULTAD";
export const CAMBIAR_PUNTUACION = "CAMBIAR_PUNTUACION";
export const CAMBIAR_DNI = "CAMBIAR_DNI"
export const CAMBIAR_SEXO = "CAMBIAR_SEXO"
export const CAMBIAR_EMAIL = "CAMBIAR_EMAIL"