export const CAMBIAR_DNI = "CAMBIAR_DNI"
export const CAMBIAR_NOMBRE = "CAMBIAR_NOMBRE"
export const CAMBIAR_SEXO = "CAMBIAR_SEXO"
export const CAMBIAR_EMAIL = "CAMBIAR_EMAIL"
export const CAMBIAR_CATEGORIA = "CAMBIAR_CATEGORIA"
export const CAMBIAR_DIFICULTAD = "CAMBIAR_DIFICULTAD";
export const CAMBIAR_PUNTUACION = "CAMBIAR_PUNTUACION";